### ISSUE TITLE
Upload all SC segmentation annotations to git-annex

### ISSUE THREAD

**Issue by uzaymacar** [ivadomed/model_seg_ms_mp2rage#34] opened 2022-01-14 15:07 UTC
Currently, only manually corrected SC segmentation annotations are included in the git-annex (`basel-mp2rage`). We should also add the automatically generated SC annotations (via `sct_deegseg_sc` as shown in the preprocessing script) there.

**Comment by jcohenadad** [comment] 2023-01-24 19:49
duplicate of #55

**Closed as completed by jcohenadad** 2023-01-24 19:49 UTC
